---
title: "R 배열 Array"
author:
  - name: Bohak Maeng
    url: https://manboha.github.io
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

배열은 동일한 형태의 데이터가 2차원 이상으로 구성된 데이터 구조입니다. 벡터가 1차원이고, 행렬은 2차원, 배열은 2차원 이상의 구조입니다. 배열은 행렬을 층층히 쌓으면서 3차원, 4차원, 5차원 등으로 확대할 수 있습니다.

## 배열 생성 Create array

```{r}
# 1~24의 숫자를 3x4 행렬의 2층 짜리 배열 만들기
arr1 <- array(1:24, dim = c(3, 4, 2))
arr1
```

## 배열 이름 붙이기 Set names of array

```{r}
# array()의 dimnames 속성을 이용하여 이름 붙이기
arr2 <- array(
  data = 1:24,
  dim = c(4, 3, 2),
  dimnames = list(c("one", "two", "three", "four"),
                  c("ray", "karl", "mimo"),
                  c("steve", "mark")
                  )
  )
arr2
```

## 배열의 요소 추출 Accessing array elements

### 특정위치에 있는 요소 추출

```{r}
# 2행, 2열, 2층 요소 추출
arr2[2, 2, 2]

# 각 층의 2행 추출
arr2[2, , ]

# 각층의 3행, 3열 요소 추출
arr2[3, 3, ]

# 2층의 행렬 추출
arr2[,,2]
```

### 이름으로 요소 추출

```{r}
# 2행(two), 2열(karl), 2층(mark) 요소 추출
arr2["two", "karl", "mark"]

# 각 층의 2행(two) 추출
arr2["two", , ]

# 각층의 3행(three), 3열(mimo) 요소 추출
arr2["three", "mimo", ]

# 2층(mark)의 행렬 추출
arr2[,,"mark"]
```

### 마이너스 기호(-)를 이용하여 요소 제외

```{r}
# 2행과 2열 제외
arr2[-2, -2, ]
```

### 조건으로 요소 추출

```{r}
# 11초과인 값 추출
arr2[arr2 > 11]

# 짝수 추출
arr2[arr2 %% 2 == 0]
```

## 배열 요소 수정 Modify array

```{r}
arr2[2, 2, 1] <- 55
arr2
```

## 배열 연산

```{r}
arr2 * 3
```

```{r}
rowSums(arr2)
colSums(arr2)
```

배열의 차원이 같다면 배열끼리 계산이 가능합니다.

```{r}
ax <- array(1:12, dim = c(2, 3, 2))
ay <- array(11:22, dim = c(2, 3, 2))
ax; ay

ax + ay
ax * ay
ax / ay
ax + (1:2)
```

