---
title: "R 데이터 프레임 Data frame"
author:
  - name: Bohak Maeng
    url: https://manboha.github.io
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 데이터 프레임은 다양한 형태의 데이터가 2차원으로 구성된 데이터 구조입니다. 행(케이스)과 열(변수)로 구성된 표와 같이 생겼습니다. 엑셀에서 이름 필드, 연령 필드, 성적 필드 등으로 이루어진 표와 같다고 보면 됩니다. 통계분석에 가장 많이 사용됩니다.

○ 데이터 프레임(Data Frame)이란?
  - 데이터 프레임은 행(케이스)과 열(변수)로 구성된 표와 같이 생겼습니다. 엑셀에서 이름 필드, 연령 필드, 성적 필드 등으로 이루어진 표와 같다고 보면 됩니다. 통계분석에 가장 많이 사용됩니다.

○ 데이터 프레임 만들기

age <- c(24, 28, 31, 25, 27, 22, 29)
sex <- c("남", "여", "여", "남", "여", "남", "여")
score <- c(90, 80, 85, 75, 95, 80, 70)
df <- data.frame(age, sex, score)  # age, sex, score 변수를 묶어 데이터 프레임 만들기


 2) 데이터 프레임의 생성
      - 데이터 프레임을 생성하는 방법은 많습니다. 그 중에서 가장 많이 쓰이는 방법은 엑셀에서 정리된 데이터를 R에서 읽어 들이는 방법입니다. 이 방법은 조금 있다 설명 드리겠습니다.
      - 두 번째 방법은 벡터 형식의 자료를 묶어서 데이터 프레임을 만드는 것입니다. 아래 예제는 data.frame 함수를 이용하여 벡터 변수 a와 b를 묶어서 ab라는 데이터 프레임을 만드는 것입니다. 이때 age=a 처럼 변수명을 새롭게 지정할 수 있습니다. 여기서는 변수명 a를 age로 변경하였습니다.

a <- c(24, 28, 31, 25, 27, 22, 29)
b <- c("남", "여", "여", "남", "여", "남", "여")
ab <- data.frame(a, b)
ab
   a  b
1 24 남
:  :  :
7 29 여
ab <- data.frame(age=a, sex=b)
ab
   age  sex
1   24   남
:    :    :

  
   3) 데이터 프레임에서 데이터 조회
     - 데이터 프레임의 행과 열 개수 조회하기 : nrow, ncol, str

nrow(ab)  # [1] 7
ncol(ab)  # [1] 2
str(ab)
'data.frame':   7 obs. of  2 variables:
 $ age: num  24 28 31 25 27 22 29
 $ sex: Factor w/ 2 levels "남","여": 1 2 2 1 2 1 2

     - 데이터 프레임의 변수 조회하기 : 데이터프레임명$변수명

ab$age  # [1] 24 28 31 25 27 22 29
ab[,1]  # [1] 24 28 31 25 27 22 29
mean(ab$age)  # [1] 26.57143   mean은 평균을 구하는 함수, mean(ab[,1])

     - 데이터 프렘임의 데이터 조회하기

head(ab)
  age sex
1  24  남
:   :   :
6  22  남
head(ab, 3)
  age sex
1  24  남
2  28  여
3  31  여
ab[1:3,]
  age sex
1  24  남
2  28  여
3  31  여
ab[2,]
  age sex
2  28  여


   3) 데이터 프레임에서 조건에 맞는 데이터를 추출해서 새로운 데이터프레임 만들기
      - 특정 조건에 맞는 데이터만 추출하고 싶을 경우 subset 함수를 이용하거나 대괄호 안에 조건식을 입력하여 추출합니다.
      - (주의) 비교 할 때 “같다”라는 기호는 = 이 아니라 == 입니다.  

ab2 <- subset(ab, sex=="여")
ab2
  age sex
2  28  여
3  31  여
5  27  여
7  29  여
ab3 <- ab[ab$sex=="여",]  # 데이터가 많을 경우 subset 함수보다 속도가 더 빠름
ab3
  age sex
2  28  여
3  31  여
5  27  여
7  29  여
ab[ab$age>30,]
  age sex
3  31  여



○ 데이터 프레임에서 데이터 조회

str(df)  # 데이터 프레임의 구조를 보여줌
df$age  # df 데이터 프레임의 age 변수에 있는 값을 출력
df$age[2]  # age 변수의 두 번째 값 28 출력
mean(df$age)  # df의 age의 산술평균 구함   26.57143
